---
- name: Deploy and Run Python Application on Jenkins Node
  hosts: jenkins_nodes
  become: yes

  tasks:
    - name: Copy the Python app to the Jenkins node
      copy:
        src: /workspaces/jenkins_codespace/hello.py  # Path to the Python app on the Ansible control machine
        dest: /home/ec2-user/hello.py  # Path on the Jenkins node
        mode: '0755'  # Ensure the file is executable

    - name: Run the Python application
      command: python3 /home/ec2-user/hello.py
      register: script_out

    - name: Displaying output
      debug:
        var: script_out.stdout_lines
